config/routes.rb
Rails.application.routes.draw do
  root to: "recipes#index"
  resources :recipes, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contentful/chef.rb
# frozen_string_literal: true

class Contentful::Chef < ContentfulModel::Base
  self.content_type_id = 'chef'
end

app/models/contentful/recipe.rb
# frozen_string_literal: true

class Contentful::Recipe < ContentfulModel::Base
  self.content_type_id = 'recipe'

  has_one :chef, class_name: 'Contentful::Chef'

  def photo_url
    photo.fields.try(:[], :file)&.url
  end
end

app/models/contentful/tag.rb
# frozen_string_literal: true

class Contentful::Tag < ContentfulModel::Base
  self.content_type_id = 'tag'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  def index
    @recipes = Contentful::Recipe.all.load
  end

  def show
    @recipe = Contentful::Recipe.find(show_params[:id])
  end

  private

  def show_params
    params.permit(:id)
  end
end

app/helpers/application_helper.rb
require 'redcarpet'

module ApplicationHelper
  def render_markdown(markdown)
    renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    renderer.render(markdown).html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Twitter Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav id="main-nav" class="navbar navbar-dark bg-dark mb-5">
      <div class="container">
        <%= link_to 'Recipes', root_path %>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_image.html.erb
<img
  class="card-img-top"
  src="<%= recipe.photo_url %>"
  alt="<%= recipe.title %>"
>

app/views/recipes/_listing.html.erb
<div class="col-sm-6">
  <div class="card mb-3">
    <%= render partial: 'image', locals: { recipe: listing } %>

    <div class="card-body">
      <h5 class="card-title">
        <%= listing.title %>
      </h5>

      <p class="card-text">
        <%= link_to 'View this recipe', recipe_path(listing.id) %>
      </p>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<h1 class="mb-3">All Recipes</h1>

<div class="row">
  <% @recipes.each do |recipe| %>
    <%= render partial: 'listing', object: recipe %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="row mb-5">
  <div class="col">
    <%= link_to 'View all recipes', root_path %>
  </div>
</div>

<div class="row">
  <div class="col col-lg-6">
    <%= render partial: 'image', locals: { recipe: @recipe } %>
  </div>

  <div class="col col-lg-6">
    <h1 class="mb-3"><%= @recipe.title %></h1>

    <% if @recipe.chef&.name.present? %>
      <i class="chef-name">by <%= @recipe.chef&.name %></i>
    <% end %>

    <% (@recipe.tags || []).each do |tag| %>
      <span class="badge badge-light">
        <%= tag.name %>
      </span>
    <% end %>

    <p class="mt-3">
      <%= render_markdown(@recipe.description) %>
    </p>
  </div>
</div>